создал модуль аутентификации и регистрации, добавил БД, внес изменени…
NickolayBabulich/booking_of_services pull request #9
Opened 2024-03-20 23:20 UTC by NickolayBabulich

…я в структуру проекта  task#8

2024-03-21 09:02 UTC, lwof requested changes
Найс, что выпилил бутстрап. 

Теперь надо что-то с create_app решить.

2024-03-21 09:02 UTC, lwof commented on app/config.py
> +SECRET_KEY = 'fdsf432twgwhH^#2tergsfd2fhT%Y$22GFGfdsgbb2t2g2%@%@2gfgdg22@2gfg1165FG@dfdbt4tT4$fgd'
Я бы изменил это на значение на что-то вроде 'dev_key'

2024-03-21 09:02 UTC, lwof commented on create_db.py
> +with create_app().app_context():
Но ведь у тебя в проекте сейчас нет `create_app()` 😅

2024-03-21 22:16 UTC, NickolayBabulich commented on create_db.py
> +with create_app().app_context():
Добавил вторым коммитом)

2024-03-21 22:20 UTC, NickolayBabulich commented on app/config.py
> +SECRET_KEY = 'fdsf432twgwhH^#2tergsfd2fhT%Y$22GFGfdsgbb2t2g2%@%@2gfgdg22@2gfg1165FG@dfdbt4tT4$fgd'
попробовал изменить сразу отваливается flask wtf
<img width="1131" alt="Screenshot 2024-03-22 at 10 19 42" src="https://github.com/NickolayBabulich/booking_of_services/assets/137121548/17392551-166d-4381-b08e-d5fa9e1db7f7">
Я так понимаю он ждет только константу SECRET_KEY

2024-03-25 01:05 UTC, merged

2024-03-26 14:08 UTC, lwof reviewed
👍

2024-03-26 14:08 UTC, lwof commented on app/auth/models/models.py
> +    password = db.Column(db.String(120), nullable=False)
Можно кстати не указывать длину строки, будет работать тоже норм.

2024-03-26 14:08 UTC, lwof commented on app/config.py
> +SECRET_KEY = 'fdsf432twgwhH^#2tergsfd2fhT%Y$22GFGfdsgbb2t2g2%@%@2gfgdg22@2gfg1165FG@dfdbt4tT4$fgd'
Да, да, ему нужна эта штука. Я про значение говорил: `SECRET_KEY = 'dev_key'`